name: Add checklist
on:
  issues:
    types: [labeled]

jobs:
  update-proceedings:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    env:
      checklist_version: "1.1"

    steps:
      - name: Check labels
        id: check_labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.issue.labels.map(label => label.name);
            const hasApproved = labels.includes('approved');
            const hasChecklist = labels.includes('checklist');
            return hasApproved && hasChecklist;
      
      - name: Early exit
        if: steps.check_labels.outputs.result == 'false'
        run: echo "Not an approved checklist issue - exiting"

      - name: Checkout
        if: steps.check_labels.outputs.result == 'true'
        uses: actions/checkout@v4

      - name: Extract checklist data
        if: steps.check_labels.outputs.result == 'true'
        run: |
          # Extract checklist
          issue_body='${{ github.event.issue.body }}'
          checklist_json=$(echo "$issue_body" | sed -n '/```json/I,/```/p' | sed '1d;$d')
          name=$(echo "$checklist_json" | jq -r '.name' | sed -e 's/ /_/g' -e 's/-/_/g')

          # Add date, evaluators, history
          date_str=$(date +%F)
          issue_json='${{ toJson(github.event.issue) }}'
          evaluators=$(jq -r '[.assignees[] | {name: .login, contact: .html_url}]' <<< "$issue_json")
          history="https://github.com/nmind/proceedings/commits/development/src/lib/data/entries/checklist_${name}.json"
          image="brain_9_svgrepo_com--CadetBlue.png"

          # Add additional checklist items
          checklist_json=$(echo "$checklist_json" | jq \
            --arg checklist_version "$checklist_version" \
            --arg date "$date_str" \
            --argjson evaluators "$evaluators" \
            --arg history "$history" \
            --arg image "$image" \
            '. + {checklist_version: $checklist_version, date: $date, evaluators: $evaluators, history: $history, image: $image}')
          echo $checklist_json

          # Export variables to environment
          echo "checklist=$(echo $checklist_json)" >> $GITHUB_ENV
          echo "name=$(echo $name)" >> $GITHUB_ENV

      - name: Create file
        if: steps.check_labels.outputs.result == 'true'
        run: |
          file_name="src/lib/data/entries/checklist_${{ env.name }}.json"
          echo "file_name=$(echo $file_name)" >> $GITHUB_ENV
          echo '${{ env.checklist }}' | jq . > $file_name

      - name: Validate checklist
        if: steps.check_labels.outputs.result == 'true'
        uses: GrantBirki/json-yaml-validate@v3
        with:
          base_dir: src/lib/data/entries
          json_schema: .github/static/checklist_schema.json
          ajv_strict_mode: false
          files: ${{ env.file_name }}
      
      - name: Configure git
        if: steps.check_labels.outputs.result == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
        
      - name: Commit files
        if: steps.check_labels.outputs.result == 'true'
        run: |
          git add ${{ env.file_name }}
          git commit -m 'Closes #${{ github.event.issue.number }}'
          git push 

      # Badge generation steps
      - name: Setup Python
        if: steps.check_labels.outputs.result == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Generate badge
        if: steps.check_labels.outputs.result == 'true'
        run: |
          badge_url=$(python .github/scripts/create_badge.py "${{ env.file_name }}")
          echo "badge=$(echo $badge_url)" >> $GITHUB_ENV
      
      - name: Comment on issue
        if: steps.check_labels.outputs.result == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ **Your new NMIND badge has been generated!**: 
            ![${{ env.name }}](${{ env.badge }})

            🔗 **Badge URL**:
            ```
            ${{ env.badge }}
            ```

            📄 **To embed this badge in a `README.md`, use the following Markdown:**
            ```md
            [![${{ env.name }}](${{ env.badge }})](https://nmind.org/proceedings/${{ env.name }})
            ```
            