name: Add checklist
on:
  issues:
    types: [labeled]
concurrency:
  group: checklist-workflow
  cancel-in-progress: false

jobs:
  update-proceedings:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Check labels
        id: check_labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.issue.labels.map(label => label.name);
            const hasApproved = labels.includes('approved');
            const hasChecklist = labels.includes('checklist');
            return hasApproved && hasChecklist;

      - name: Early exit
        if: steps.check_labels.outputs.result == 'false'
        run: |
          echo "Not an approved checklist issue - exiting"
          exit 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract checklist data
        run: |
          issue_body='${{ github.event.issue.body }}'
          checklist=$(echo "$issue_body" | sed -n '/```json/I,/```/p' | sed '1d;$d')
          echo "checklist=$(echo $checklist)" >> $GITHUB_ENV
          raw_name=$(echo "$checklist" | jq -r '.name')
          echo "raw_name=$(echo $raw_name)" >> context.env
          name=$(echo $raw_name | sed -e 's/ /_/g' -e 's/-/_/g')
          echo "name=$(echo $name)" >> $GITHUB_ENV

      - name: Create file
        run: |
          file_name="src/lib/data/entries/checklist_${{ env.name }}.json"
          echo "file_name=$(echo $file_name)" >> $GITHUB_ENV
          echo '${{ env.checklist }}' | jq . > $file_name

      - name: Validate checklist
        uses: GrantBirki/json-yaml-validate@v3
        with:
          base_dir: src/lib/data/entries
          json_schema: .github/static/checklist_schema.json
          ajv_strict_mode: false
          files: ${{ env.file_name }}
      
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit files
        run: |
          git add ${{ env.file_name }}
          git commit -m 'Closes #${{ github.event.issue.number }}'
          git push 

      # Badge generation steps
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Generate badge
        run: |
          badge_url=$(python .github/scripts/create_badge.py "${{ env.file_name }}")
          echo "badge=$(echo $badge_url)" >> $GITHUB_ENV

      # Generate url-safe, directly from checklist (env.name already altered)
      - name: Generate URL-safe tool string
        run: |
          tool_url=$(echo "$checklist" \
            | jq -r '.name' \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/[^a-z0-9_ ]//g' \
            | tr ' ' '-')
          echo "safe_url=$(echo $tool_url)" >> $GITHUB_ENV
      
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ **Your new NMIND badge has been generated!**: 
            ![${{ env.name }}](${{ env.badge }})

            🔗 **Badge URL**:
            ```
            ${{ env.badge }}
            ```

            📄 **To embed this badge in a `README.md`, use the following Markdown:**
            ```md
            [![${{ env.name }}](${{ env.badge }})](https://nmind.org/proceedings/${{ env.safe_url }})
            ```
      
      # Update context for passing to other workflows
      - name: Update context
        run: |
            echo "issue_number=${{ github.event.issue.number }}" >> context.env
      
      - name: Upload context
        uses: actions/upload-artifact@v4
        with:
          name: context
          path: context.env
          retention-days: 1